import Head from "next/head";
import { PostCard, Categories, PostWidget } from "../components";
import { getPosts } from "../services";
import { FeaturedPosts } from "../sections";
import Masonry from "react-masonry-css";

export default function Home({ posts }) {
  const breakpointColumnsObj = {
    default: 3,
    1100: 3,
    900: 2,
    700: 2,
    600: 1,
    500: 1,
  };

  return (
    <div className="container mx-auto px-9 mb-8">
      <Head>
        <title>sári-sarì</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <FeaturedPosts />
      <Masonry
        breakpointCols={breakpointColumnsObj}
        className="my-masonry-grid"
        columnClassName="my-masonry-grid_column"
      >
        {posts.map((post, index) => (
          <PostCard post={post.node} key={index} />
        ))}
      </Masonry>
    </div>
  );
}

export async function getStaticProps() {
  const posts = (await getPosts()) || [];

  return {
    props: { posts },
  };
}
