import "./globals.css";
import { Cormorant } from "@next/font/google";
import Navbar from "../components/Navbar";
import Footer from "../components/Footer";
import ShopProvider from "../context/shopContext";

const cormorant = Cormorant({ subsets: ["latin"] });

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="scroll-smooth">
      <head>
        <title>Quiet Kids Club</title>
        <meta name="description" content="Generated by create next app" />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1.0"
        ></meta>
        <link rel="icon" href="/favicon.ico" />
      </head>
      <body className={`${cormorant.className} bg-neutral-50`}>
        <ShopProvider>
          <Navbar />
          {children}
          <Footer />
        </ShopProvider>
      </body>
    </html>
  );
}
