import type { NextPage } from 'next'
import Head from 'next/head'

import Masthead from '../components/masthead';
import AboutUs from '../components/aboutus';
import Skills from '../components/skills';
import Works from '../components/works';
import Tech from '../components/tech';
import Contact from '../components/contact';
import Footer from '../components/footer';
import useSWR from 'swr';

const fetcher = (input: any, init?: any) =>
  fetch(input, init).then(res => res.json())

const Home: NextPage = () => {
  const { data } = useSWR('/api/stats', fetcher)
  
  return (
    <div>
      <Head>
        <title>Arthur Laroya</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.svg" />
      </Head>

      <Masthead />
      <AboutUs />
      <Skills commits={data?.commits} />
      <Works />
      <Tech />
      <Contact />
      <Footer />
    </div>
  )
}

export default Home
